# This is a basic workflow to help you get started with Actions

name: PIP zip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DownloadPips-linux-27:
    name: Download Pips for Python ${{ matrix.version }} on ${{ matrix.os }}
    strategy:
      # max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        version: ["2.7"]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    container:
      image: registry.access.redhat.com/ubi7
      volumes:
        - ${{ github.workspace }}:/repo
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        run: |
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py > get-pip.py
          python get-pip.py
          pip --no-python-version-warning config set global.no-python-version-warning true
          pip config set global.use-feature 2020-resolver
          python -m pip install --upgrade pip setuptools wheel setuptools-scm
          mkdir -p pips
          cd pips
          if [ -f ../requirements-${{ matrix.version }}.txt ]; then
            cat ../requirements-${{ matrix.version }}.txt | xargs -n1 -d '\n' pip download ;
            pip download -r ../requirements-${{ matrix.version }}.txt;
          fi
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: pips/
  DownloadPips-linux-38:
    name: Download Pips for Python ${{ matrix.version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ["3.8"]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    container:
      image: registry.access.redhat.com/ubi7/python-38
      volumes:
        - ${{ github.workspace }}:/repo
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pip and setup folder, download
        run: |
          python -m pip install --upgrade pip setuptools wheel setuptools-scm
          mkdir -p pips
          cd pips
          if [ -f ../requirements-${{ matrix.version }}.txt ]; then
            cat ../requirements-${{ matrix.version }}.txt | xargs -n1 -d '\n' pip download ;
            pip download -r ../requirements-${{ matrix.version }}.txt;
          fi
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: pips/
  DownloadPips-Windows:
    name: Download Pips for Python ${{ matrix.version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: ${{ matrix.version }}
          # The target architecture (x86, x64) of the Python or PyPy interpreter.
          architecture: x64
      - name: Install pip and setup folder
        run: |
          python -m pip install --upgrade pip setuptools wheel setuptools-scm
          mkdir -p pips
      - name: Download packages - Windows
        run: |
          cd pips
          if (Test-Path '../requirements-${{ matrix.version }}.txt') {
            cat '../requirements-${{ matrix.version }}.txt' | %{pip download $_};
            pip download -r '../requirements-${{ matrix.version }}.txt';
          }
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: pips/
