# This is a basic workflow to help you get started with Actions

name: PIP zip

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DownloadPips-linux-27:
    name: Download Pips for Python 2.7 on RHEL 7
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi7
      volumes:
        - ${{ github.workspace }}:/repo
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        run: |
          yum update -y
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py > get-pip.py
          python get-pip.py
          pip --no-python-version-warning config set global.no-python-version-warning true
          pip config set global.use-feature 2020-resolver
          python -m pip install --upgrade pip setuptools wheel setuptools-scm
          mkdir -p pips
      - name: Download packages
        run: |
          cd pips
          if [ -f ../requirements-2.7-rhel7.txt ]; then
            cat ../requirements-2.7-rhel7.txt | xargs -n1 -d '\n' pip download ;
            pip download -r ../requirements-2.7-rhel7.txt;
          fi
      - name: Download downloaded
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: downloaded
      - name: Check if files already downloaded
        run: |
          touch downloaded.sha512
          cd pips
          for file in pips/*; do
            if sha512sum -c --status <(grep "$file" ../downloaded.sha512); then
              echo "$file already downloaded, removing..."
              rm "$file"
            else
              sha512sum "$file" >> ../downloaded.sha512
            fi
          done
      - name: Upload pips
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: pips
          path: pips
      - name: Upload downloaded
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: downloaded
          path: downloaded.sha512

  DownloadPips-linux-36:
    name: Download Pips for Python 3.6 on RHEL 7
    needs: ["DownloadPips-linux-27"]
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi7
      volumes:
        - ${{ github.workspace }}:/repo
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        run: |
          yum update -y
          yum install rh-python36 -y
          scl_source rh-python36
          python -m pip install --upgrade pip setuptools wheel setuptools-scm
          mkdir -p pips
      - name: Download packages
        run: |
          scl_source rh-python36
          cd pips
          if [ -f ../requirements-3.6-rhel7.txt ]; then
            cat ../requirements-3.6-rhel7.txt | xargs -n1 -d '\n' pip download ;
            pip download -r ../requirements-3.6-rhel7.txt;
          fi
      - name: Download downloaded
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: downloaded
      - name: Check if files already downloaded
        run: |
          touch downloaded.sha512
          cd pips
          for file in pips/*; do
            if sha512sum -c --status <(grep "$file" ../downloaded.sha512); then
              echo "$file already downloaded, removing..."
              rm "$file"
            else
              sha512sum "$file" >> downloaded.sha512
            fi
          done
      - name: Upload pips
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: pips
          path: pips
      - name: Upload downloaded
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: downloaded
          path: downloaded.sha512

  DownloadPips-linux-38:
    name: Download Pips for Python 3.8 on RHEL 7
    needs: ["DownloadPips-linux-27", "DownloadPips-linux-36"]
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi7
      volumes:
        - ${{ github.workspace }}:/repo
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        run: |
          yum update -y
          yum install rh-python38 -y
          scl_source rh-python38
          python -m pip install --upgrade pip setuptools wheel setuptools-scm
          mkdir -p pips
      - name: Download packages
        run: |
          scl_source rh-python38
          cd pips
          if [ -f ../requirements-3.8-rhel7.txt ]; then
            cat ../requirements-3.8-rhel7.txt | xargs -n1 -d '\n' pip download ;
            pip download -r ../requirements-3.8-rhel7.txt;
          fi
      - name: Download downloaded
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: downloaded
      - name: Check if files already downloaded
        run: |
          touch downloaded.sha512
          cd pips
          for file in pips/*; do
            if sha512sum -c --status <(grep "$file" ../downloaded.sha512); then
              echo "$file already downloaded, removing..."
              rm "$file"
            else
              sha512sum "$file" >> downloaded.sha512
            fi
          done
      - name: Upload pips
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: pips
          path: pips
      - name: Upload downloaded
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: downloaded
          path: downloaded.sha512


  DownloadPips-windows-27:
    name: Download Pips for Python 2.7 on Windows
    needs: ["DownloadPips-linux-27", "DownloadPips-linux-36", "DownloadPips-linux-38"]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: "2.7"
          # The target architecture (x86, x64) of the Python or PyPy interpreter.
          architecture: x64
      - name: Install pip and setup folder
        run: |
          pip --no-python-version-warning config set global.no-python-version-warning true
          pip config set global.use-feature 2020-resolver
          python -m pip install --upgrade pip setuptools wheel setuptools-scm
          mkdir -p pips
      - name: Download packages
        run: |
          cd pips
          if (Test-Path '../requirements-2.7-windows.txt') {
            cat '../requirements-2.7-windows.txt' | %{pip download $_};
            pip download -r '../requirements-2.7-windows.txt';
          }
      - name: Download downloaded
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: downloaded
      - name: Check if files already downloaded
        run: |
          if (!(Test-Path downloaded.sha512)) {
            New-Item -ItemType File downloaded.sha512 | Out-Null
          }
          foreach ($file in Get-ChildItem -Path pips) {
            $hash = Get-FileHash $file.FullName -Algorithm SHA512 | Select-Object -ExpandProperty Hash
            Write-Host "Checking file $($file.Name)"
            if (Select-String -Path downloaded.sha512 -Pattern "^$hash $file.Name") {
              Write-Host "File $($file.Name) has already been downloaded. Deleting..."
              Remove-Item -Path $file.FullName -Force
            }
            else {
              Write-Host "File $($file.Name) has not been downloaded yet. Adding to downloaded..."
              Add-Content -Path downloaded.sha512 -Value "$hash $($file.Name)"
            }
          }
          Get-Content downloaded.sha512 | Sort-Object -Unique { $_.Split()[0] } | Set-Content downloaded.sha512
      - name: Upload pips
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: pips
          path: pips
      - name: Upload downloaded
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: downloaded
          path: downloaded.sha512

  DownloadPips-Windows:
    name: Download Pips for Python ${{ matrix.version }} on Windows
    needs: ["DownloadPips-linux-27", "DownloadPips-linux-36", "DownloadPips-linux-38", "DownloadPips-windows-27"]
    strategy:
      max-parallel: 1
      matrix:
        os: [windows-latest]
        version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: ${{ matrix.version }}
          # The target architecture (x86, x64) of the Python or PyPy interpreter.
          architecture: x64
      - name: Install pip and setup folder
        run: |
          python -m pip install --upgrade pip setuptools wheel setuptools-scm
          mkdir -p pips
      - name: Download packages
        run: |
          cd pips
          if (Test-Path '../requirements-2.7-windows.txt') {
            cat '../requirements-2.7-windows.txt' | %{pip download $_};
            pip download -r '../requirements-2.7-windows.txt';
          }
      - name: Download downloaded
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: downloaded
      - name: Check if files already downloaded
        run: |
          if (!(Test-Path downloaded.sha512)) {
            New-Item -ItemType File downloaded.sha512 | Out-Null
          }
          foreach ($file in Get-ChildItem -Path pips) {
            $hash = Get-FileHash $file.FullName -Algorithm SHA512 | Select-Object -ExpandProperty Hash
            Write-Host "Checking file $($file.Name)"
            if (Select-String -Path downloaded.sha512 -Pattern "^$hash $file.Name") {
              Write-Host "File $($file.Name) has already been downloaded. Deleting..."
              Remove-Item -Path $file.FullName -Force
            }
            else {
              Write-Host "File $($file.Name) has not been downloaded yet. Adding to downloaded..."
              Add-Content -Path downloaded.sha512 -Value "$hash $($file.Name)"
            }
          }
          Get-Content downloaded.sha512 | Sort-Object -Unique { $_.Split()[0] } | Set-Content downloaded.sha512
      - name: Upload pips
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: pips
          path: pips
      - name: Upload downloaded
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: downloaded
          path: downloaded.sha512
